
services:
  mysql:
    image: mysql
    restart: always
    environment:
      MYSQL_DATABASE: 'exercicioJpaDB'
      MYSQL_ROOT_PASSWORD: '123456'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: '123456'
    ports:
      - 3310:3306
    volumes:
      - my-db:/var/lib/mysql
volumes:
  my-db:
